"use client";

import { Users, Home, Phone } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, FormEvent } from "react";
import toast from "react-hot-toast";

import { addMembers } from "@/app/services/members/members"; // adjust to your actual path

interface FormFieldLabelProps {
  icon?: React.ReactNode;
  children: React.ReactNode;
}

function FormFieldLabel({ icon, children }: FormFieldLabelProps) {
  return (
    <label className="mb-2 flex items-center gap-2 text-sm font-bold text-font">
      {icon}
      {children}
    </label>
  );
}

export default function TambahWarga() {
  const [namaWarga, setNamaWarga] = useState("");
  const [rtWarga, setRtWarga] = useState("");
  const [noTelp, setNoTelp] = useState("");
  const [nomorNasabah] = useState(""); // auto-generated by the system
  const [catatan, setCatatan] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const router = useRouter();

  const resetForm = () => {
    setNamaWarga("");
    setRtWarga("");
    setNoTelp("");
    setCatatan("");
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (!namaWarga.trim()) {
      toast.error("Nama warga wajib diisi.");
      return;
    }

    try {
      setIsSubmitting(true);

      // NOTE: catatan isn't part of AddMemberPayload yet — the backend has
      // no field for it, so it's currently kept local-only and not sent.
      // picName/picPhone/unitIds are unit-only fields with no equivalent
      // in this form, so they're sent as empty/null for an individual.
      const member = await addMembers({
        fullName: namaWarga.trim(),
        type: "INDIVIDUAL",
        rt: rtWarga.trim() || null,
        phone: noTelp.trim() || null,
        picName: null,
        picPhone: null,
        unitIds: [],
      });

      toast.success(`Warga "${namaWarga.trim()}" berhasil ditambahkan.`);
      router.push("/data-warga");
    } catch (err) {
      toast.error(
        err instanceof Error
          ? err.message
          : "Terjadi kesalahan, silakan coba lagi.",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const inputClass =
    "w-full rounded-md bg-placeholder/50 px-4 py-3 text-sm text-font placeholder:text-font/50 outline-none focus:ring-2 focus:ring-primary transition duration-300";

  return (
    <div className="min-h-full bg-white rounded-md p-6">
      <form onSubmit={handleSubmit}>
        {/* Nama Warga */}
        <div className="mb-6">
          <FormFieldLabel icon={<Users size={18} />}>Nama Warga</FormFieldLabel>
          <input
            type="text"
            value={namaWarga}
            onChange={(e) => setNamaWarga(e.target.value)}
            placeholder="Isi nama warga"
            className={inputClass}
          />
        </div>

        {/* RT Warga / Nomor Telepon Warga / Nomor Nasabah */}
        <div className="mb-6 grid grid-cols-1 gap-6 md:grid-cols-3">
          <div>
            <FormFieldLabel icon={<Home size={16} />}>RT Warga</FormFieldLabel>
            <input
              type="text"
              value={rtWarga}
              onChange={(e) => setRtWarga(e.target.value)}
              placeholder="Isi RT warga"
              className={inputClass}
            />
          </div>

          <div>
            <FormFieldLabel icon={<Phone size={16} />}>
              Nomor Telepon Warga
            </FormFieldLabel>
            <input
              type="tel"
              value={noTelp}
              onChange={(e) => setNoTelp(e.target.value)}
              placeholder="Isi nomor telepon warga"
              className={inputClass}
            />
          </div>

          <div>
            <FormFieldLabel>Nomor Nasabah</FormFieldLabel>
            <input
              type="text"
              value={nomorNasabah}
              readOnly
              disabled
              placeholder="Dibuat otomatis setelah disimpan"
              className={`${inputClass} cursor-not-allowed opacity-80`}
            />
          </div>
        </div>

        {/* Catatan Opsional */}
        <div className="mb-6">
          <label className="mb-2 block text-sm font-bold text-font">
            Catatan Opsional
          </label>
          <textarea
            value={catatan}
            onChange={(e) => setCatatan(e.target.value)}
            rows={8}
            className="w-full resize-none rounded-md bg-placeholder/50 px-4 py-3 text-sm text-font outline-none focus:ring-2 focus:ring-primary transition duration-300"
          />
        </div>

        {/* Actions */}
        <div className="flex items-center gap-4">
          <button
            type="button"
            onClick={() => router.back()}
            disabled={isSubmitting}
            className="rounded-md bg-placeholder px-8 py-3 font-semibold text-white transition hover:opacity-75 cursor-pointer duration-300 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Kembali
          </button>
          <button
            type="button"
            onClick={resetForm}
            disabled={isSubmitting}
            className="rounded-md bg-danger px-8 py-3 text-sm font-semibold text-white transition hover:opacity-75 cursor-pointer duration-300 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Ulang
          </button>
          <button
            type="submit"
            disabled={isSubmitting}
            className="rounded-md bg-primary px-8 py-3 text-sm font-semibold text-white transition hover:opacity-75 cursor-pointer duration-300 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {isSubmitting ? "Menyimpan..." : "Simpan"}
          </button>
        </div>
      </form>
    </div>
  );
}
