import { Prisma } from "@/generated/prisma/client";
import { getPrisma } from "@/infrastructure/database/prisma";
import type { CreateWithdrawalInput, ListWithdrawalsInput } from "@/modules/withdrawals/withdrawal.schema";
import { AppError } from "@/shared/errors/app-error";

const include = { member: { select: { memberNumber: true, fullName: true } } } as const;
type RecordWithMember = Prisma.WithdrawalGetPayload<{ include: typeof include }>;
function dto(record: RecordWithMember) { return { id: record.id, memberId: record.memberId, memberNumber: record.member.memberNumber, memberName: record.member.fullName, status: record.status, amount: record.amount.toString(), notes: record.notes, rejectionReason: record.rejectionReason, approvedAt: record.approvedAt?.toISOString() ?? null, paidAt: record.paidAt?.toISOString() ?? null, createdAt: record.createdAt.toISOString() }; }
function invalid(message: string): AppError { return new AppError({ code: "INVALID_WITHDRAWAL_STATE", message, statusCode: 409 }); }
async function balance(client: Prisma.TransactionClient | ReturnType<typeof getPrisma>, organizationId: string, memberId: string): Promise<Prisma.Decimal> {
  const groups = await client.financialLedger.groupBy({ by: ["entryType"], where: { organizationId, memberId }, orderBy: { entryType: "asc" }, _sum: { amount: true } });
  const credit = groups.filter(({ entryType }) => entryType === "DEPOSIT" || entryType === "ADJUSTMENT").reduce((sum, row) => sum.add(row._sum?.amount ?? 0), new Prisma.Decimal(0));
  const debit = groups.filter(({ entryType }) => entryType === "WITHDRAWAL" || entryType === "REVERSAL").reduce((sum, row) => sum.add(row._sum?.amount ?? 0), new Prisma.Decimal(0));
  return credhttps://github.com/farrasmumtaz/EcoPoin/pull/20/conflict?name=ep-be%252Fsrc%252Fmodules%252Fwithdrawals%252Fwithdrawal.service.ts&base_oid=cb8d124e5ced92823d516b8f276c432bf187bc57&head_oid=5cbc51f937c5d5af047ad6f0f9309a67ee4a7b45it.sub(debit);
}
export async function listWithdrawals(organizationId: string, input: ListWithdrawalsInput) {
  const prisma = getPrisma(); const where: Prisma.WithdrawalWhereInput = { organizationId, ...(input.status ? { status: input.status } : {}), ...(input.search ? { member: { OR: [{ fullName: { contains: input.search, mode: "insensitive" } }, { memberNumber: { contains: input.search, mode: "insensitive" } }] } } : {}) }; const skip = (input.page - 1) * input.limit;
  const [records, total] = await prisma.$transaction([prisma.withdrawal.findMany({ where, include, orderBy: { createdAt: "desc" }, skip, take: input.limit }), prisma.withdrawal.count({ where })]);
  return { items: records.map(dto), pagination: { page: input.page, limit: input.limit, total, totalPages: Math.ceil(total / input.limit) } };
}
export async function createWithdrawal(organizationId: string, actorId: string, input: CreateWithdrawalInput) {
  const member = await getPrisma().member.findFirst({ where: { id: input.memberId, organizationId, isActive: true }, select: { id: true } }); if (!member) throw new AppError({ code: "MEMBER_NOT_FOUND", message: "Active member was not found.", statusCode: 404 });
  const amount = new Prisma.Decimal(input.amount); if ((await balance(getPrisma(), organizationId, input.memberId)).lt(amount)) throw new AppError({ code: "INSUFFICIENT_BALANCE", message: "Saldo tabungan tidak mencukupi.", statusCode: 422 });
  const record = await getPrisma().$transaction(async (tx) => { const created = await tx.withdrawal.create({ data: { organizationId, memberId: input.memberId, amount, notes: input.notes, requestedBy: actorId }, include }); await tx.auditLog.create({ data: { organizationId, actorId, action: "WITHDRAWAL_REQUESTED", entityType: "withdrawal", entityId: created.id, metadata: { amount: amount.toString() } } }); return created; }); return dto(record);
}
export async function approveWithdrawal(organizationId: string, actorId: string, id: string) { const current = await getPrisma().withdrawal.findFirst({ where: { id, organizationId }, include }); if (!current) throw new AppError({ code: "WITHDRAWAL_NOT_FOUND", message: "Withdrawal was not found.", statusCode: 404 }); if (current.status !== "REQUESTED") throw invalid("Only a REQUESTED withdrawal can be approved."); const record = await getPrisma().withdrawal.update({ where: { id }, data: { status: "APPROVED", approvedBy: actorId, approvedAt: new Date() }, include }); return dto(record); }
export async function rejectWithdrawal(organizationId: string, actorId: string, id: string, reason: string) { const current = await getPrisma().withdrawal.findFirst({ where: { id, organizationId }, select: { status: true } }); if (!current) throw new AppError({ code: "WITHDRAWAL_NOT_FOUND", message: "Withdrawal was not found.", statusCode: 404 }); if (current.status !== "REQUESTED") throw invalid("Only a REQUESTED withdrawal can be rejected."); const record = await getPrisma().withdrawal.update({ where: { id }, data: { status: "REJECTED", rejectionReason: reason, rejectedAt: new Date(), approvedBy: actorId }, include }); return dto(record); }
export async function payWithdrawal(organizationId: string, actorId: string, id: string) {
  const record = await getPrisma().$transaction(async (tx) => { const current = await tx.withdrawal.findFirst({ where: { id, organizationId }, include }); if (!current) throw new AppError({ code: "WITHDRAWAL_NOT_FOUND", message: "Withdrawal was not found.", statusCode: 404 }); if (current.status === "PAID") return current; if (current.status !== "APPROVED") throw invalid("Only an APPROVED withdrawal can be paid."); if ((await balance(tx, organizationId, current.memberId)).lt(current.amount)) throw new AppError({ code: "INSUFFICIENT_BALANCE", message: "Saldo tabungan tidak mencukupi saat pembayaran.", statusCode: 422 }); await tx.financialLedger.create({ data: { organizationId, memberId: current.memberId, withdrawalId: id, entryType: "WITHDRAWAL", amount: current.amount, referenceKey: `withdrawal:${id}`, createdBy: actorId } }); const paid = await tx.withdrawal.update({ where: { id }, data: { status: "PAID", paidBy: actorId, paidAt: new Date() }, include }); await tx.auditLog.create({ data: { organizationId, actorId, action: "WITHDRAWAL_PAID", entityType: "withdrawal", entityId: id, metadata: { amount: current.amount.toString() } } }); return paid; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); return dto(record);
}
