"use client";

import { ArrowLeft, Banknote, Recycle, Receipt, Wallet } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getMemberSummary, type MemberSummary } from "@/app/services/members/members";

const money = (value: string): string => `Rp${Number(value).toLocaleString("id-ID")}`;
const weight = (value: string): string => `${Number(value).toLocaleString("id-ID", { maximumFractionDigits: 3 })} kg`;
const transactionLabels = { DRAFT: "Draft", FINALIZED: "Menunggu Pencairan", COMPLETED: "Selesai", CANCELLED: "Dibatalkan", VOIDED: "Void" } as const;
const ledgerLabels = { DEPOSIT: "Kredit Setoran", WITHDRAWAL: "Penarikan", REVERSAL: "Reversal", ADJUSTMENT: "Penyesuaian" } as const;

function DetailWargaContent() {
  const router = useRouter(); const id = useSearchParams().get("id") ?? ""; const [data, setData] = useState<MemberSummary | null>(null);
  useEffect(() => { if (!id) { toast.error("ID warga tidak valid."); return; } let active = true; void getMemberSummary(id).then((result) => { if (active) setData(result); }).catch((error: unknown) => toast.error(error instanceof Error ? error.message : "Detail warga gagal dimuat.")); return () => { active = false; }; }, [id]);
  if (!data) return <div className="p-8 text-sm text-gray-500">Memuat detail warga...</div>;
  const cards = [{ label: "Saldo", value: money(data.statistics.balance), icon: <Wallet size={18} /> }, { label: "Total Setoran", value: money(data.statistics.totalDepositAmount), icon: <Banknote size={18} /> }, { label: "Total Berat", value: weight(data.statistics.totalWeightKg), icon: <Recycle size={18} /> }, { label: "Transaksi Selesai", value: String(data.statistics.completedTransactions), icon: <Receipt size={18} /> }];
  return <div className="min-h-full bg-gray-50 p-6"><button type="button" onClick={() => router.back()} className="flex items-center gap-2 text-sm font-semibold text-gray-600 hover:text-primary"><ArrowLeft size={18} /> Kembali</button>
    <div className="mt-5 rounded-xl border border-gray-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-sm font-semibold text-primary">{data.member.memberNumber}</div><h1 className="mt-1 text-2xl font-bold text-gray-900">{data.member.fullName}</h1><p className="mt-1 text-sm text-gray-500">{data.member.rt ?? "RT belum diisi"} · {data.member.phone ?? "Telepon belum diisi"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${data.member.activityStatus === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : "bg-gray-100 text-gray-600"}`}>{data.member.activityStatus === "ACTIVE" ? "Aktif" : data.member.activityStatus === "NEVER_ACTIVE" ? "Belum pernah transaksi" : "Tidak aktif"}</span></div></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <div key={card.label} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-semibold text-primary">{card.icon}{card.label}</div><div className="mt-2 text-xl font-bold text-gray-900">{card.value}</div></div>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-gray-200 bg-white shadow-sm"><h2 className="border-b border-gray-200 px-5 py-4 font-bold text-gray-900">Riwayat Setoran</h2><div className="overflow-auto"><table className="w-full text-sm text-gray-800"><thead className="bg-gray-50"><tr><th className="px-5 py-3 text-left">Tanggal</th><th className="px-5 py-3 text-left">Status</th><th className="px-5 py-3 text-right">Berat</th><th className="px-5 py-3 text-right">Nilai</th></tr></thead><tbody>{data.transactions.length === 0 ? <tr><td colSpan={4} className="p-8 text-center text-gray-500">Belum ada setoran.</td></tr> : data.transactions.map((transaction) => <tr key={transaction.id} className="border-t border-gray-100"><td className="px-5 py-3">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(transaction.createdAt))}</td><td className="px-5 py-3">{transactionLabels[transaction.status]}</td><td className="px-5 py-3 text-right">{weight(transaction.totalWeightKg)}</td><td className="px-5 py-3 text-right font-semibold">{money(transaction.totalAmount)}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-xl border border-gray-200 bg-white shadow-sm"><h2 className="border-b border-gray-200 px-5 py-4 font-bold text-gray-900">Mutasi Tabungan</h2><div className="overflow-auto"><table className="w-full text-sm text-gray-800"><thead className="bg-gray-50"><tr><th className="px-5 py-3 text-left">Tanggal</th><th className="px-5 py-3 text-left">Jenis</th><th className="px-5 py-3 text-right">Nominal</th></tr></thead><tbody>{data.ledgerEntries.length === 0 ? <tr><td colSpan={3} className="p-8 text-center text-gray-500">Belum ada mutasi.</td></tr> : data.ledgerEntries.map((entry) => { const credit = entry.entryType === "DEPOSIT" || entry.entryType === "ADJUSTMENT"; return <tr key={entry.id} className="border-t border-gray-100"><td className="px-5 py-3">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(entry.createdAt))}</td><td className="px-5 py-3">{ledgerLabels[entry.entryType]}</td><td className={`px-5 py-3 text-right font-bold ${credit ? "text-emerald-600" : "text-red-600"}`}>{credit ? "+" : "-"}{money(entry.amount)}</td></tr>; })}</tbody></table></div></section></div>
  </div>;
}

export default function DetailWarga() { return <Suspense fallback={<div className="p-8 text-sm text-gray-500">Memuat halaman...</div>}><DetailWargaContent /></Suspense>; }
