"use client";

import { Check, Search, WalletCards, X } from "lucide-react"; import { useEffect, useState } from "react"; import toast from "react-hot-toast";
import { getMembers, type Member } from "@/app/services/members/members"; import { approveWithdrawal, createWithdrawal, getWithdrawals, payWithdrawal, rejectWithdrawal, type Withdrawal, type WithdrawalStatus } from "@/app/services/withdrawals/withdrawals";
const LABELS: Record<WithdrawalStatus, string> = { REQUESTED: "Menunggu", APPROVED: "Disetujui", PAID: "Dibayar", REJECTED: "Ditolak" }; const money = (value: string): string => `Rp${Number(value).toLocaleString("id-ID")}`;
export default function Penarikan() {
  const [items, setItems] = useState<readonly Withdrawal[]>([]); const [members, setMembers] = useState<readonly Member[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState<WithdrawalStatus | "">(""); const [memberId, setMemberId] = useState(""); const [amount, setAmount] = useState(""); const [notes, setNotes] = useState(""); const [refresh, setRefresh] = useState(0); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void Promise.all([getWithdrawals({ search: search || undefined, status: status || undefined, limit: 100 }), getMembers({ limit: 100 })]).then(([withdrawals, memberResult]) => { if (!active) return; setItems(withdrawals.items); setMembers(memberResult.items.filter((member) => member.isActive)); }).catch((error: unknown) => toast.error(error instanceof Error ? error.message : "Data penarikan gagal dimuat.")); return () => { active = false; }; }, [refresh, search, status]);
  const run = async (action: () => Promise<Withdrawal>, success: string): Promise<void> => { setBusy(true); try { await action(); toast.success(success); setRefresh((value) => value + 1); } catch (error: unknown) { toast.error(error instanceof Error ? error.message : "Proses gagal."); } finally { setBusy(false); } };
  const submit = async (): Promise<void> => { if (!memberId || Number(amount) <= 0) { toast.error("Pilih nasabah dan isi nominal yang valid."); return; } await run(() => createWithdrawal({ memberId, amount: Number(amount), notes: notes.trim() || undefined }), "Permintaan penarikan dibuat."); setAmount(""); setNotes(""); };
  return <div className="min-h-full bg-gray-50 p-6"><div><h1 className="text-2xl font-bold text-gray-900">Penarikan Tabungan</h1><p className="mt-1 text-sm text-gray-500">Kelola permintaan, persetujuan, dan pembayaran penarikan.</p></div>
    <section className="mt-6 rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-gray-900"><WalletCards size={19} /> Buat Permintaan</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><select value={memberId} onChange={(event) => setMemberId(event.target.value)} className="h-11 rounded-lg border border-gray-300 bg-white px-3 text-sm"><option value="">Pilih nasabah/unit</option>{members.map((member) => <option key={member.id} value={member.id}>{member.memberNumber} - {member.fullName}</option>)}</select><input type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Nominal penarikan" className="h-11 rounded-lg border border-gray-300 px-3 text-sm" /><input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Catatan opsional" className="h-11 rounded-lg border border-gray-300 px-3 text-sm" /><button type="button" disabled={busy} onClick={() => void submit()} className="h-11 rounded-lg bg-primary px-5 font-semibold text-white disabled:opacity-50">Buat Permintaan</button></div></section>
    <div className="mt-5 flex gap-3"><div className="relative flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari nasabah" className="w-full rounded-xl border border-gray-200 bg-white py-3 pl-11 pr-4 text-sm" /></div><select value={status} onChange={(event) => setStatus(event.target.value as WithdrawalStatus | "")} className="rounded-xl border border-gray-200 bg-white px-4 text-sm"><option value="">Semua status</option>{Object.entries(LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    <section className="mt-5 overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div className="overflow-auto"><table className="w-full min-w-[900px] text-sm text-gray-800"><thead className="bg-gray-50"><tr><th className="px-5 py-4 text-left">Tanggal</th><th className="px-5 py-4 text-left">Nasabah</th><th className="px-5 py-4 text-right">Nominal</th><th className="px-5 py-4 text-center">Status</th><th className="px-5 py-4 text-right">Aksi</th></tr></thead><tbody>{items.length === 0 ? <tr><td colSpan={5} className="p-10 text-center text-gray-500">Belum ada permintaan penarikan.</td></tr> : items.map((item) => <tr key={item.id} className="border-t border-gray-100"><td className="px-5 py-4">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(item.createdAt))}</td><td className="px-5 py-4"><strong className="block">{item.memberName}</strong><span className="text-xs text-gray-500">{item.memberNumber}</span></td><td className="px-5 py-4 text-right font-bold">{money(item.amount)}</td><td className="px-5 py-4 text-center"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold">{LABELS[item.status]}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2">{item.status === "REQUESTED" && <><button disabled={busy} type="button" onClick={() => void run(() => approveWithdrawal(item.id), "Penarikan disetujui.")} title="Setujui" className="flex h-9 w-9 items-center justify-center rounded-md border border-primary text-primary"><Check size={16} /></button><button disabled={busy} type="button" onClick={() => { const reason = window.prompt("Alasan penolakan:"); if (reason?.trim()) void run(() => rejectWithdrawal(item.id, reason.trim()), "Penarikan ditolak."); }} title="Tolak" className="flex h-9 w-9 items-center justify-center rounded-md border border-danger text-danger"><X size={16} /></button></>}{item.status === "APPROVED" && <button disabled={busy} type="button" onClick={() => { if (window.confirm("Konfirmasi uang telah diserahkan?")) void run(() => payWithdrawal(item.id), "Penarikan dibayar dan saldo didebit."); }} className="rounded-md bg-primary px-3 py-2 text-xs font-bold text-white">Bayar</button>}</div></td></tr>)}</tbody></table></div></section>
  </div>;
}
